name: build

on:
  push:
    schedule:
      - cron: '0 2 * * *'
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:

jobs:
  arm64:
    runs-on: arvato
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Docker Meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v6.2.0
        with:
          images: ghcr.io/arvatoaws-labs/sfn-ng
          flavor: |
            latest=false
            suffix=-arm64
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
            {{major}}
      - name: Login to GitHub Packages Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4.6.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          #username: jenkins-arvato
          #password: ${{ secrets.CR_PAT }}
      - name: Build and Push
        id: build
        uses: docker/build-push-action@v7.4.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          pull: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
  amd64:
    runs-on: arvato-x86
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Docker Meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v6.2.0
        with:
          images: ghcr.io/arvatoaws-labs/sfn-ng
          flavor: |
            latest=false
            suffix=-amd64
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
            {{major}}
      - name: Login to GitHub Packages Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4.6.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          #username: jenkins-arvato
          #password: ${{ secrets.CR_PAT }}
      - name: Build and Push
        id: build
        uses: docker/build-push-action@v7.4.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          pull: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
  manifest:
    runs-on: arvato
    needs: [arm64, amd64]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Docker Meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v6.2.0
        with:
          images: ghcr.io/arvatoaws-labs/sfn-ng
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
            {{major}}
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v4.6.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          #username: jenkins-arvato
          #password: ${{ secrets.CR_PAT }}
      - name: Create Docker Manifest
        if: steps.docker_meta.outputs.tags != ''
        uses: int128/docker-manifest-create-action@v2.29.0
        with:
          index-annotations: ${{ steps.docker_meta.outputs.labels }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          sources: |
            ghcr.io/arvatoaws-labs/sfn-ng@${{ needs.arm64.outputs.image-digest }}
            ghcr.io/arvatoaws-labs/sfn-ng@${{ needs.amd64.outputs.image-digest }}
